### ISSUE TITLE
invalid directory structure and missing botocore

### ISSUE THREAD

**Issue by impressiver** [revmischa/sublime-boto3#1] opened 2016-08-27 04:37 UTC
I'm trying to get [sublime-awslambda](/revmischa/sublime-awslambda) installed via Package Control 3, but there seems to be an issue importing `boto3` (declared in `dependencies.json`). Package Control does successfully download and install the `sublime-boto3`, but importing results in an empty module.

I was able to track down half of the problem: the contents of `sublime-boto3/all` (minus the readme's, pkg-info, license, etc.) should be placed in a subdirectory `sublime-boto3/all/boto3`.

Doing the above gets classes loading as expected, until `boto3` tries to import `botocore`, which is not available in the Package Control dependencies.

Console output when trying to run `sublime-awslambda` "list functions" from the menu:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 553, in run_
    return self.run()
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 294, in run
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 182, in select_function
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 168, in _load_functions
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 66, in client
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 49, in test_aws_credentials_exist
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 43, in get_aws_session
AttributeError: 'module' object has no attribute 'session'
```

Trying to import `boto3`:

```
>>> import boto3
>>> dir(boto3)
['__doc__', '__initializing__', '__loader__', '__name__', '__package__', '__path__']
```

After moving `boto3` module sources to `sublime-boto3/all/boto3/`:

```
reloading plugin AWS Lambda.awslambda
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 658, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "awslambda in /Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/AWS Lambda.sublime-package", line 14, in <module>
  File "/Users/ian/Library/Application Support/Sublime Text 3/Packages/boto3/all/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/Users/ian/Library/Application Support/Sublime Text 3/Packages/boto3/all/boto3/session.py", line 17, in <module>
    import botocore.session
ImportError: No module named 'botocore'
```

**Comment by revmischa** [comment] 2016-08-27 08:39
That is interesting because this seemed to totally work for me for this plugin: https://github.com/revmischa/sublime-awslambda
But maybe I already had botocore installed system-wide or something. 
So you think we need to lump botocore in with this module? Or what?

**Comment by impressiver** [comment] 2016-08-27 19:28
I'm not quite sure, yet. This is my first dive under the hood with Package Control 3 dependencies, and the whole thing seems kinda unmaintainable. I assume there's a reason why ST3 can't simply maintain its own virtualenv for deps, but manually repackaging and republishing deps without version control is a train wreck.

I `pip install`'d boto3 but it wasn't found by ST3. I'll try creating the botocore dependency package and see if that makes things work.

**Comment by impressiver** [comment] 2016-08-27 19:36
I'm sure I could manually configure additional `sys.path` entries to find additional system packages, but from what I've gathered that's not how sublime packages are intended to work. Might be a hack to make it work for me, but not a solution for everyone.

**Comment by revmischa** [comment] 2016-08-27 20:01
I agree it's incredibly cumbersome. If you figure it out do send a PR.

**Comment by RonWang** [comment] 2016-08-29 23:24
I collected all the files/ file folders and copy-paste it under the ".../Sublime Text 3/Packages/ " 
then I can run the code for one time. But the next time I opened the Sublime Text 3, the "boto3" folder is updated by ST3, automatically, even disable the check_update option. Is there a auto-update scheme in the code?

**Comment by revmischa** [comment] 2016-08-29 23:27
Not in the plugin code no. I think it fetches a tag from github. If you figure out how to fix this problem send me a pull request!

**Comment by revmischa** [comment] 2016-08-29 23:27
Maybe someone needs to make a botocore sublime dep package? Or bundle it in this one somehow?

**Comment by impressiver** [comment] 2016-08-29 23:49
Adding a `botocore` dependency package to PC3 should do the trick (this time). I'll give it a shot when I get the chance.

**Comment by revmischa** [comment] 2016-08-30 03:54
I removed boto3 from being installed system-wide. I am still able to import it just fine within sublime. How can I reproduce what you're seeing?

![screen shot 2016-08-29 at 8 53 58 pm](https://cloud.githubusercontent.com/assets/245131/18075567/cafe7afe-6e2a-11e6-9d3b-1adc8afd4f90.png)

**Comment by impressiver** [comment] 2016-08-31 03:19
What's your `sys.path`? The issue is loading `botocore` as a dependency of `boto3` (a dependency of a dependency). `botocore.session` is imported on line 17 of `boto3/all/boto3/session.py`. So `botocore` has to be found _somewhere_.

**Comment by impressiver** [comment] 2016-08-31 03:23
I uploaded an initial attempt at a [sublime-botocore](/impressiver/sublime-botocore), would you mind checking for sanity? I'm not sure how to configure Package Control to use a local clone of the `package_control_channel` (modified to include `sublime-botocore` in `repository/dependencies.json`) to test it out.

**Comment by revmischa** [comment] 2016-08-31 03:29
['/Users/bobo/Library/Application Support/Sublime Text 3/Packages/Python Flake8 Lint/contrib', '/Applications/Sublime Text.app/Contents/MacOS', '/Applications/Sublime Text.app/Contents/MacOS/python3.3.zip', '/Users/bobo/Library/Application Support/Sublime Text 3/Packages', '/Users/bobo/Library/Application Support/Sublime Text 3/Packages/boto3/all', '/Users/bobo/Library/Application Support/Sublime Text 3/Packages/bz2/st3_osx_x64', '/Users/bobo/Library/Application Support/Sublime Text 3/Packages/requests/all']

**Comment by revmischa** [comment] 2016-08-31 03:30
botocore is in '/Users/bobo/Library/Application Support/Sublime Text 3/Packages/boto3/all'. It doesn't need to be packaged separately since it's in my sys.path. See the screenshot above. What's your path?

**Comment by impressiver** [comment] 2016-08-31 03:35
`boto3.session` is in `.../Sublime Text 3/Packages/boto3/all/boto3/session.py`, but `boto3.session` imports `botocore.session`.

My `sys.path`:

```
[
  '/Applications/Sublime Text.app/Contents/MacOS',
  '/Applications/Sublime Text.app/Contents/MacOS/python3.3.zip',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/pygments/all',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/boto3/all',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/bz2/st3_osx_x64',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/markupsafe/all',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/python-markdown/st3',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/requests/all',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/python-jinja2/all',
  '/Users/ian/Library/Application Support/Sublime Text 3/Packages/mdpopups/st3',
  '/Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/libs',
  '/Users/ian/Library/Application Support/Sublime Text 3/Installed Packages/JsFormat.sublime-package/src'
]
```

**Comment by revmischa** [comment] 2016-08-31 04:19
I have botocore/session.py in bobo3/all. Do you? 
![screen shot 2016-08-30 at 9 19 18 pm](https://cloud.githubusercontent.com/assets/245131/18115834/7c1ee158-6ef7-11e6-9d2f-8b97c90db6f3.png)

**Comment by impressiver** [comment] 2016-08-31 04:28
This is what the directory looks like when Package Control installs `boto3` automatically:
![image](https://cloud.githubusercontent.com/assets/125022/18115901/1a66a9cc-6ef8-11e6-857e-2595632c8df3.png)

Notice how all the `boto3` source files are directly in `all` instead of under `boto3/all/boto3/`. There's also no `botocore` (my package reflects the structure of this repo). Is it possible you have local commits that haven't been pushed yet? Is your `Packages/boto3` a symlink?

**Comment by impressiver** [comment] 2016-08-31 04:49
Ah, I think I figured it out.

The [1.4.0 upgrade commit](/sublime-boto3/commit/4f17afd015aa801fab36e09a22f665ac9402d635) blew away the old directory structure, I bet your local install is an old version. Maybe try deleting the package and reinstalling?

**Comment by revmischa** [comment] 2016-08-31 05:13
Okay, figured it out. When I refetched boto3 with pip it only left me the .pyc files, which are git ignored, which is why they all showed up locally for me but weren't actually committed. I had to use `--no-compile` to get the .py files. I pushed a new tag v1.4.1 let's see if it's chill now

**Comment by impressiver** [comment] 2016-08-31 05:16
Here's some confirmation that dependencies aren't updated until a user-facing package which depends on it is updated: https://forum.sublimetext.com/t/dependencies-in-package-control-3/14646/12

**Comment by impressiver** [comment] 2016-08-31 05:19
I wrote [a simple bash script](/impressiver/sublime-botocore/blob/master/update.sh) to pull version releases from Github instead of using installed packages. Just change the vars at the top and it should work for this too.

**Comment by revmischa** [comment] 2016-08-31 05:21
Cool but that really shouldn't be needed. botocore should come bundled with this dependency. 
I pushed a new version tag of AWSLambda which depends on this.

**Comment by revmischa** [comment] 2016-08-31 05:23
Let me know if you experience any more issues please.

**Closed as completed by revmischa** 2016-08-31 05:23 UTC

**Comment by impressiver** [comment] 2016-08-31 05:27
I have no personal beef bundling the deps, but apparently [they _should_ be separate](https://forum.sublimetext.com/t/dependencies-in-package-control-3/14646/6). All I wanted was lambda working in ST3 😆. Thanks!

**Comment by revmischa** [comment] 2016-08-31 05:28
Yeah they should but fuck that. What about the other deps? What about their deps? Ugh.

**Comment by impressiver** [comment] 2016-08-31 05:29
Agreed. The whole mechanism is bonkers.

**Comment by impressiver** [comment] 2016-08-31 05:34
Removed and reinstalled `awslambda`, all good 👍
